[package]
name = "lsp85"
version = "0.1.0"
edition = "2024"

[dependencies]
lsp-server = "0.7.9"
lsp-types = "0.97.0"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
serde_json = "1"
wasm-bindgen = "0.2.106"

